;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		backward-delete-char
		c-electric-paren
		c-electric-star
		cua-paste
		keyboard-quit
		nav/delete-word-back
		nav/smart-tab
		nxml-electric-slash
		undo-modern
		))

(setq mc/cmds-to-run-once
      '(
		create-and-move-to-newline-below
		describe-key
		highlight-then-select-next
		mouse-set-region
		nav/toggle
		omnisharp-go-to-definition
		))
